mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: poke
  username: root
  password: Eric_191021
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false